### ISSUE TITLE
Cant find the SampleController.java file

### ISSUE THREAD

**Issue by EDelfosse** [bitbrawl/foodfight#1]
Hey, I cant seem to find the SampleController file. I imported the .git and it gave me foodfight, foodfight-api,foodfight-engine,foodfight-runner, foodfight-server, and sample-players folders, I see a src/main/java folder in foodfight-api however I dont see an org.bitbrawl.foodfight package, just an  org.bitbrawl.foodfight.util package, and no SampleController file.
Thanks

Edit: I also cant find the Debug class that the getting started page mentions

Edit: I figured out the problem. I was looking at this repo not my personal one. You may wanna specify that in the 'getting started'

**Comment by fvoichick** [comment]
Thanks! I just added a clarifying sentence to the Getting Started page.
